services:
  server:
    image: server 
    container_name: server 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 12345:12345
    volumes:
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12345/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@gmail.com" 
      ZO_ROOT_USER_PASSWORD: "helloworld" 
      ZO_HTTP_AUTH_BASIC_USER: "root@gmail.com" 
      ZO_HTTP_AUTH_BASIC_PASSWORD: "helloworld" 
    ports:
      - "5081:5080"
    volumes:
      - openobserve:/data

volumes:
  scalar_db:
  openobserve: