services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scalar-api 
    ports:
      - "5432:5432"
    volumes:
      - scalar_db:/var/lib/postgresql/data


  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@gmail.com"
      ZO_ROOT_USER_PASSWORD: "helloworld"
    ports:
      - "5080:5080"
    volumes:
      - openobserve:/data

volumes:
  scalar_db:
  openobserve: