services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@gmail.com"
      ZO_ROOT_USER_PASSWORD: "helloworld"
    ports:
      - "5081:5080"
    volumes:
      - openobserve:/data

volumes:
  scalar_db:
  openobserve: